apiVersion: v1
kind: Service
metadata:
    name: membership-form
    labels: &labels
        app.kubernetes.io/name: membership-form
spec:
    selector: *labels
    ports:
        - name: http
          port: 80
          targetPort: http
