version: '3'

services:
  app:
    image: vivaconagua/membership-form:latest
    build: 
      context: . 
      dockerfile: Dockerfile.dev
    restart: always
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    networks:
      domain_net:
        ipv4_address: ${docker_ip}

networks:
  domain_net:
    external:
      name: domain_net

